from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional

class ExtractionResult(BaseModel):
    """Result of a general JSON or key-value extraction task."""
    raw_text: str = Field(description="The raw string output generated by the model.")
    fields: Dict[str, Any] = Field(default_factory=dict, description="Parsed JSON fields extracted from the document.")
    latency_ms: float = Field(description="Inference latency in milliseconds.")
    num_tokens_generated: int = Field(description="Number of tokens generated by the model.")

class QAResult(BaseModel):
    """Result of a question answering task."""
    question: str = Field(description="The question that was asked.")
    answer: str = Field(description="The answer generated by the model.")
    latency_ms: float = Field(description="Inference latency in milliseconds.")
    num_tokens_generated: int = Field(description="Number of tokens generated by the model.")

class TableResult(BaseModel):
    """Result of a table extraction task."""
    raw_table: str = Field(description="The raw table output from the model (e.g., HTML structure).")
    markdown: str = Field(description="Markdown representation of the extracted table.")
    latency_ms: float = Field(description="Inference latency in milliseconds.")
    num_tokens_generated: int = Field(description="Number of tokens generated by the model.")
